language: node_js
node_js:
    - "10"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb
  - npm update -g npm
  - npm install -g grunt-cli

install:
  - sudo apt-get install -y build-essential libxmu-dev libxi-dev libglu1-mesa-dev libglew-dev
  - npm install
  - npm rebuild

cache:
  directories:
    - node_modules

script:
  - xvfb-run -s "-ac -screen 0 800x600x24" grunt combine
