version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get install -y xvfb
      - npm update -g npm
      - npm install -g grunt-cli
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - apt-get install -y build-essential libxmu-dev libxi-dev libglu1-mesa-dev libglew-dev
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - grunt combine
      - xvfb-run -s "-ac -screen 0 800x600x24" grunt animate_planets
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync --delete build/public "s3://cdn.starpeace.io/"
      - echo Build completed on `date`

artifacts:
  files:
    - build/public/**/*
