version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get install -y xvfb xauth
      - apt-get install -y build-essential libxmu-dev libxi-dev libglu1-mesa-dev libglew-dev
      - npm update -g npm
      - npm install -g grunt-cli


  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install --verbose

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - xvfb-run -s "-ac -screen 0 800x600x24" grunt combine

  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync build/public "s3://cdn.starpeace.io/"
      - echo Build completed on `date`

artifacts:
  files:
    - build/public/**/*
