version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Entered the install phase...
      - npm update -g npm

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run assets

  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync build/public "s3://cdn.starpeace.io/"
      - echo Build completed on `date`

artifacts:
  files:
    - build/public/**/*
